#pragma once

#define CIRQUE_PINNACLES_COUNT 2
#define CIRQUE_PINNACLES_DEADZONE_CENTER 0
#define CIRQUE_PINNACLES_DEADZONE_EDGES 4096
#define CIRQUE_PINNACLES_DUAL_JOYSTICKS
#define CIRQUE_PINNACLES_POINTING_DEVICE
#define CIRQUE_PINNACLES_SCROLL_REVERSE 1
#define CIRQUE_PINNACLES_SCROLL_THRESHOLD 256
#define CIRQUE_PINNACLES_SPI_CS_PIN_LEFT GP9
#define CIRQUE_PINNACLES_SPI_CS_PIN_RIGHT GP13
#define CIRQUE_PINNACLES_TAP_ZONES_X 3
#define CIRQUE_PINNACLES_TAP_ZONES_Y 3
#define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_2X
#define CIRQUE_PINNACLE_CIRCULAR_SCROLL_ENABLE
#define CIRQUE_PINNACLE_CLOCK_SPEED 10000000
#define CIRQUE_PINNACLE_CURVED_OVERLAY
#define CIRQUE_PINNACLE_DIAMETER_MM 35
#define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_ABSOLUTE_MODE
#define CIRQUE_PINNACLE_SPI_CS_PIN CIRQUE_PINNACLES_SPI_CS_PIN_RIGHT
#define CIRQUE_PINNACLE_SPI_DIVISOR 8
#define CIRQUE_PINNACLE_SPI_LSB_FIRST false
#define CIRQUE_PINNACLE_SPI_MODE 1
#define CIRQUE_PINNACLE_TAP_ENABLE
#define DYNAMIC_MACRO_NO_NESTING
#define DYNAMIC_MACRO_SIZE 256
#define I2C1_SCL_PIN GP19
#define I2C1_SDA_PIN GP18
#define I2C_DRIVER I2CD1
#define JOYSTICK_AXIS_COUNT 6
#define JOYSTICK_AXIS_RESOLUTION 10
#define JOYSTICK_BUTTON_COUNT 12
#define JOYSTICK_HAS_HAT
#define MATRIX_ROW_PINS { GP14, GP8, GP7, GP6 }
#define MATRIX_COL_PINS { GP29, GP28, GP27, GP26, GP15, GP0, GP1, GP2, GP3, GP4 }
#define OLED_BRIGHTNESS 128
#define OLED_DISPLAY_128X32
#define OLED_DISPLAY_ADDRESS 0x3C
#define PERMISSIVE_HOLD
#define POINTING_DEVICE_DEFAULT_DPI 5
#define POINTING_DEVICE_DRIVER_cirque_pinnacle_spi
// #define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define POINTING_DEVICE_MAX_DPI 16
#define POINTING_DEVICE_MIN_DPI 1
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP25
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U
#define SPI_DRIVER SPID1
#define SPI_MISO_PIN GP12
#define SPI_MOSI_PIN GP11
#define SPI_SCK_PIN GP10
#define TAPPING_TERM 300
#define TAPPING_TERM_PER_KEY
#define TAPPING_TOGGLE 2

