#pragma once

// Define options
#define DYNAMIC_MACRO_NO_NESTING
#define DYNAMIC_MACRO_SIZE 128
#define ENCODER_A_PINS { GP6 }
#define ENCODER_B_PINS { GP7 }
#define JOYSTICK_AXIS_COUNT 6
#define JOYSTICK_AXIS_RESOLUTION 10
#define JOYSTICK_BUTTON_COUNT 12
#define JOYSTICK_HAS_HAT
#define OLED_BRIGHTNESS 128
#define OLED_DISPLAY_128X64
#define OLED_DISPLAY_ADDRESS 0x3C
#define PERMISSIVE_HOLD
#define TAP_DANCE_QUAD_SUPPORT
#define TAPPING_TERM 100
#define TAPPING_TERM_PER_KEY
#define TAPPING_TOGGLE 2
#define TRI_LAYER_LOWER_LAYER 1
#define TRI_LAYER_UPPER_LAYER 2
#define TRI_LAYER_ADJUST_LAYER 3
