#pragma once

#define CIRQUE_PINNACLE_CIRCULAR_SCROLL_ENABLE
#define CIRQUE_PINNACLE_CLOCK_SPEED 10000000
#define CIRQUE_PINNACLE_DIAMETER_MM 35
#define CIRQUE_PINNACLE_SPI_CS_PIN GP5
#define CIRQUE_PINNACLE_SPI_DIVISOR 8
#define CIRQUE_PINNACLE_SPI_LSB_FIRST false
#define CIRQUE_PINNACLE_SPI_MODE 1
#define CIRQUE_PINNACLE_TAP_ENABLE
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define SPI_DRIVER SPID0
#define SPI_MISO_PIN GP4
#define SPI_MOSI_PIN GP3
#define SPI_SCK_PIN GP2
