#pragma once

// Define options
#define CIRQUE_PINNACLE_CIRCULAR_SCROLL_ENABLE
#define CIRQUE_PINNACLE_CUSTOM
#define CIRQUE_PINNACLE_DIAMETER_MM 35
#define CIRQUE_PINNACLE_TAP_ENABLE
#define DYNAMIC_MACRO_NO_NESTING
#define DYNAMIC_MACRO_SIZE 256
#define ENCODER_A_PINS {GP4, GP6 }
#define ENCODER_B_PINS { GP5, GP7 }
#define I2C_DRIVER I2CD1
#define I2C1_SCL_PIN GP3
#define I2C1_SDA_PIN GP2
#define JOYSTICK_AXIS_COUNT 6
#define JOYSTICK_AXIS_RESOLUTION 10
#define JOYSTICK_BUTTON_COUNT 12
#define JOYSTICK_HAS_HAT
#define OLED_BRIGHTNESS 128
#define OLED_DISPLAY_128X64
#define OLED_DISPLAY_ADDRESS 0x3C
#define PERMISSIVE_HOLD
#define PIMORONI_TRACKBALL_ADDRESS 0x0A
#define PIMORONI_TRACKBALL_SCALE 1
#define POINTING_DEVICE_DEFAULT_DPI 5
#define POINTING_DEVICE_DEFAULT_JS_DPI 5
#define POINTING_DEVICE_MAX_DPI 16
#define POINTING_DEVICE_MIN_DPI 1
#define TAP_DANCE_QUAD_SUPPORT
#define TAPPING_TERM 150
#define TAPPING_TERM_PER_KEY
#define TAPPING_TOGGLE 2
#define TRI_LAYER_LOWER_LAYER 1
#define TRI_LAYER_UPPER_LAYER 2
#define TRI_LAYER_ADJUST_LAYER 3
